[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = host.docker.internal
db_port = 5432
db_user = odoo15
db_password = B@0Ng0c
db_name = db_ubkt_prod_00
data_dir = /var/lib/odoo
admin_passwd = admin
workers = 2
